avocado-framework/avocado-virt

- avocado/virt/qemu/devices.py
Create a method to append an arbitrary cmdline to an already
existing QEMU cmdline, add_cmdline. That method will be useful
for many tests that seek to add devices to a QEMU based VM before
boot.
> [V2] avocado.virt.qemu.devices: Add GenericDevice to the QEMU cmdline

- avocado/virt/defaults.py
- avocado/virt/qemu/path.py
- avocado/virt/test.py
- avocado/virt/utils/video.py
- etc/avocado/conf.d/virt.conf
Add a config file for the virtualization plugin. Let users to configure aspects of the virt plugin through their `~/.config/avocado/avocado.conf` files.
> [V1] Add config file for virt plugin

- avocado/virt/qemu/machine.py
The username and password has new params location.
> avocado.virt.qemu.machine: Fix username and password path

- avocado/virt/qemu/devices.py
- avocado/virt/qemu/machine.py
- avocado/virt/test.py
Hi @lmr, @ruda,
this pull request tries to remove obstacles I popped-up when playing with avocado-virt. There is still one thing I need to investigate and fix. When the test fails (eg. `raise Exception()` as first thing in boot test's `clenaup()`, avocado hangs in `avocado.core.output.Paginator.__del__`. When I disable paginator, it works fine (I read what it should do but in reality I didn't notice difference, do we really need it? Isn't it just an unnecessary thing which can get wrong?)
Regards,
Lukáš
> Couple of adjustements to make avocado-virt simpler to start with

- avocado/plugins/virt_bootstrap.py
- avocado/virt/qemu/path.py
From a recent API change in Avocado (see https://github.com/avocado-framework/avocado/pull/413), the utility function find_command()
has been moved from avocado.utils.process to avocado.utils.path,
so we're going to use this new module location.
Signed-off-by: Rudá Moura <rmoura@redhat.com>
> virt.qemu.path: Use avocado.utils.path.find_command().

- avocado/virt/defaults.py
Depending on how the enconding quality settings make into the PIL library,
it may cause the following error:
```
Traceback (most recent call last):
File "../avocado-virt-tests/qemu/boot.py", line 31, in cleanup
self.vm.power_off()
...
File "/home/cleber/src/avocado/avocado/virt/utils/video.py", line 83, in convert_to_jpg
i.save(jpg_file, format="JPEG", quality=quality)
File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1460, in save
save_handler(self, fp, filename)
File "/usr/lib64/python2.7/site-packages/PIL/JpegImagePlugin.py", line 480, in _save
raise ValueError("Invalid quality setting")
ValueError: Invalid quality setting
```
Getting the value from the configuration file as an integer solves that.
> video enconding: get the quality encoding value as an integer

- avocado/virt/qemu/machine.py
The params path for template changed recently.
> avocado.virt.qemu.machine: Correct the template params path

- avocado/virt/qemu/machine.py
- avocado/virt/test.py
As pointed out by Rudá, virt.qemu.template.path is not a
path, but the contents of the template file itself. Let's
change virt.qemu.template.path to virt.qemu.template.contents.
CC: Rudá Moura <rmoura@redhat.com>
> virt: Fix misleading variable

- avocado/virt/qemu/devices.py
- avocado/virt/qemu/machine.py
Turns out we haven't updated all references to the new
parameters in the virt plugin code, leading to some options
in the command line that won't have an effect, such as
--take-screendumps and --record-videos. Let's fix that.
> avocado.virt.qemu: Fix use of parameters inside virt plugin

- .gitignore
- Makefile
- avocado-virt.spec
- avocado/core/plugins/virt.py
- avocado/core/plugins/virt_bootstrap.py
- avocado/virt/defaults.py
- setup.py
* avocado.plugins: Isolate avocado.plugins.virt* from being used by test developers.
* New upstream release 0.24.0.
* Add .gitignore from avocado project.
> Test API:  Refactory plugins location

- avocado/virt/qemu/devices.py
- avocado/virt/qemu/machine.py
- avocado/virt/utils/video.py
Otherwise, params.get() will understand the default value
as the path, making the value returned incorrect (None).
Let's fix that.
> avocado.virt.qemu.machine: Explicitly pass 'default' param

- avocado-virt.spec
- avocado/virt/defaults.py
- avocado/virt/qemu/machine.py
A handful of changes with regards to settings handling in the avocado virt plugin, to avoid bugs while retrieving migration timeout values.
> Fix migration timeout

- avocado-virt.spec
- setup.py
Turns out we forgot to include the configuration files
in the RPM install. Let's fix that.
> avocado-virt: Install virt.conf config file

- avocado/core/plugins/virt.py
- avocado/virt/qemu/devices.py
- avocado/virt/qemu/machine.py
- avocado/virt/qemu/path.py
- avocado/virt/test.py
- avocado/virt/utils/video.py
This patchset changes the way params are overridden from cmdline. Additionally it changes the flat names and uses key+path instead. See the descriptions for details.
v1: https://github.com/avocado-framework/avocado-virt/pull/54
Changes:
v2: Fix the "qemu_bin_dst" typo
> Make avocado-virt work with the new AvocadoParams [v2]

- avocado/core/plugins/virt_bootstrap.py
- avocado/virt/defaults.py
- avocado/virt/qemu/machine.py
- avocado/virt/test.py
While modules living under avocado.core are not intended to be
used by tests, at this point extensions are OK using it. We may,
in the (far?) future, come with an extension/plugin API definition
but this is currently out of scope.
So, for now, let's sync avocado-virt with the proposed changes on
avocado itself.
These are the changes that impact avocado-virt:
* rename of avocado.test.Test to avocado.Test
* rename of avocado.aexpect to avocado.core.aexpect
* rename of avocado.data_dir to avocado.core.data_dir
* rename of avocado.settings to avocado.core.settings
This is related to https://github.com/avocado-framework/avocado/pull/636 and was tested functionally on top of https://github.com/avocado-framework/avocado-virt/pull/54. 
> API review: sync with the avocado API changes

- avocado/core/plugins/virt.py
"avocado multiplex" was fixed and there is no need for the hack which
disabled the multiplex-tree injection when not running test.
> plugins.virt: Remove the hack for not-modifying-multiplex

- avocado-virt.spec
- avocado/virt/qemu/machine.py
- debian/control
- requirements-travis.txt
Instead of using the avocado copy (that is going to
be removed), use the system wide copy (aexpect now
can be installed through RPMs and pip).
Changes from v1:
* Updated the `avocado-virt.spec` and `debian/control` files per @ldoktor's comments.
> avocado-virt: Change aexpect dependency

- requirements-travis.txt
Inspektor 0.1.15 has a bug (it doesn't require pep8,
so people trying to use it without pep8 are in for a
treat).
With the 0.1.16 release, that bug is fixed, so, let's update.
> requirements: Update inspektor requirement to 0.1.16

- Makefile
This patch adds link/unlink targets used by main avocado Makefile.
It requires https://github.com/avocado-framework/avocado/pull/780 patch in order to work the same way as before.
> Makefile: Add link/unlink targets

- avocado/core/plugins/virt.py
- avocado/virt/qemu/machine.py
- avocado/virt/test.py
- avocado/virt/utils/video.py
This is an automated mass import cleanup across all
avocado-virt source files:
1) Imports follow the order:
* Standard library imports
* Non standard library external imports
* Internal imports
All separated by a single line
2) One line between imports and the rest of the code
3) Remove unused imports in the process
> avocado-virt: Mass import cleanup

- avocado/core/plugins/virt.py
- requirements-travis.txt
This new version should know which pylint/astroid
combination to use on py 2.6.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
> requirements-travis.txt: Require inspektor 0.2.0

- Makefile
With the recent change in avocado, the link/unlink targets should also
call "python setup.py develop --user" (--uninstall) to enable/disable
egg links.
> Makefile: Add "python setup.py develop --user" to the "link" target

- avocado-virt.spec
So far the RPM packages have not been strict about the version
of avocado that they require.  The same version has probably
been used because of newer package availability on the repos.
Anyway, let's require the same package versions so that users
may not be surprised with breakage because of different version
and interfaces.
> SPEC file: require avocado package of the same version

- avocado_virt/plugins/virt.py
- avocado_virt/plugins/virt_bootstrap.py
This patch adjusts the code to work with the new non-View logging
approach.
This needs to be merged together with https://github.com/avocado-framework/avocado/pull/1040
> avocado_virt: Stop using the removed "View" for logging

- avocado_virt/plugins/virt.py
The `args.default_multiplex_tree` is renamed to
`default_avocado_params` in `avocado`.
__This has to be merged together with https://github.com/avocado-framework/avocado/pull/1138 PR__
> avocado_virt.plugins: Rename the `args.default_multiplex_tree`

- avocado_virt/defaults.py
- avocado_virt/plugins/virt_bootstrap.py
- docs/source/GetStartedGuide.rst
The recent change on Avocado-VT makes JeOS 23 the default image.
Let's change it here accordingly.
> JeOS: update default image to JeOS 23

- avocado_virt/qemu/machine.py
The position of arguments in "avocado.core.remoter" changed which caused
the "port" being used as "pam_file" instead making all tests fail with
SystemExit from fabric. This patch uses "port=port" to avoid such
problems in the future.
> avocado_virt: Fix remoter params

- docs/source/GuestConfiguration.rst
… yaml file.
The commit 8185537 removed restore image related cmdline options.
This patch removed related original descriptions in doc and indicates users how
add doc how to skip backup restore process via plugin config file or
to skip the backup restore process via plugin config file or yaml file.
v1: https://github.com/avocado-framework/avocado-virt/pull/81
Changes:
```yaml
v2: Use '``' around the terms
```
> doc: Improve doc regarding skipping the image restore [v2]

- avocado_virt/plugins/virt.py
- avocado_virt/plugins/virt_bootstrap.py
This adjusts, while keeping compatibility, with the proposed change
for a better module name and location for the plugin interface
definitions.
This is related to https://github.com/avocado-framework/avocado/pull/1235
> RFC: Plugin interfaces: adjustments for changes in Avocado

- avocado_virt/test.py
The `tag` argument had been removed from avocado and needs to be removed
from this plugin as well.
> avocado_virt: Remove the tag

- avocado_virt/qemu/machine.py
Depending on the qemu version, the chardev is auto-removed on
vm poweroff. Let's not make the test to fail on os.remove exception.
Signed-off-by: Amador Pahim <apahim@redhat.com>
> Don't raise exception on os.remove() during power_off()

- docs/source/GetStartedGuide.rst
Since we're dropping the distribution of avocado-virt packages, the
documentation should only refer to source based installs.
> docs: update installation instructions

- avocado_virt/qemu/machine.py
On Fedora 24, the boot test hangs for me. Adding -enable-kvm to the QEMU
command line fixes it. While I haven't digged into why it hangs with
TCG, adding -enable-kvm if possible is useful nevertheless.
Test the accessibility of /dev/kvm file, which is the universal entry to
KVM, and add -enable-kvm to the command line if available.
Also add a line of log once the decision is done.
Thanks to Amador Pahim <apahim@redhat.com> for the help on this patch.
Signed-off-by: Fam Zheng <famz@redhat.com>
---
This fixes issue #88.
> qemu: Use KVM if possible

- avocado_virt/qemu/monitor.py
The `power_on` hangs when the qemu process does not start. This patch adds
a timeout to socket.socket so it does not take forever waiting for the
vm socket.
Reference: https://trello.com/c/rydcCFFD
Signed-off-by: Amador Pahim <apahim@redhat.com>
> avocado-virt set socket timeout

- docs/source/GetStartedGuide.rst
The URL for the github repository was incorrect. Fix it.
> Fix URL typo on Getting Started Guide

- avocado_virt/qemu/machine.py
The `avocado.core.remoter` had been moved to an optional plugin called
`avocado-runner-remote`. Let's adjust the code in order to work with the
latest avocado.
Currently this module is not shipped to pip so don't depend on it just
yet, but we'll have to add this requirement later.
> avocado_virt: Adjust the code to cope with Remoter location change

- avocado_virt/defaults.py
- avocado_virt/plugins/virt.py
- avocado_virt/plugins/virt_bootstrap.py
- avocado_virt/test.py
- docs/source/GetStartedGuide.rst
This syncs Avocado-Virt with the changes already present on
Avocado-VT: the image compression method is now xz, and the
default JeOS version is 25.
> JeOS: switch to JeOS version 25 and compression based on xz

- avocado_virt/defaults.py
- avocado_virt/plugins/virt.py
This introduces a change to the style of the defaults set in
`avocado_virt/defaults.py`, but most importantly, it documents them.
This is the type of setting that will affect most users' experiences,
so it makes sense to publish that information as explicitly as
possible.
> Reorganize and document defaults

- avocado_virt/plugins/virt_bootstrap.py
By keeping the original (compressed one) and forcing the overwriting
of previous existing decompressed image.
> Bootstrap: fix the decompression of the JeOS image file

- avocado_virt/test.py
First commit fixes small bug in _restore_guest_images which fails under some circumstances and the second uses long args to improve readability (suggested in v1 by @apahim)
v1: https://github.com/avocado-framework/avocado-virt/pull/101
Changes:
```yaml
v2: New commit to use long arguments
v2: Use long arguments in existing args as well
```
> test: Improve image restore

- Makefile
The "etc" config file locations moved to "avocado/etc", adjust the "make
link" target to use both locations when "conf.d" dir exists.
> Makefile: Adjust "etc" config location for "make link"

- avocado_virt/plugins/virt.py
- avocado_virt/plugins/virt_bootstrap.py
- docs/source/GetStartedGuide.rst
The last commit changes the ways we inject default params, because in https://github.com/avocado-framework/avocado/pull/2449 this old interface is getting removed. The first 3 commits are some bugfixes found while working on this. Even with those fixes I can't really pass the `boot` test because of https://trello.com/c/H2XKgVHo/1246-avocado-virt-add-memory-to-cmdline-to-avoid-guest-issues but with manual adjustments it works well.
v1: https://github.com/avocado-framework/avocado-virt/pull/104
Changes:
```yaml
v2: Fixed typo in "FAILED TO GET DOWNLOADED FROM AVOCADO-PROJECT"
v2: Improved the "FILE DOES NOT EXIST LOCALLY"
v2: Removed the change from 205 to hundreds as it's accurate
```
> Use avocado variants API and some bugfixes [v2]
